/**
 * Golden parity: the TypeScript engine must reproduce models/tests/golden.json
 * (generated by the Python engine) exactly, for every model in /models.
 * Run: pnpm --filter web test
 */
import { strict as assert } from "node:assert";
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { parse } from "yaml";

import { evaluate, evaluateRange, FormulaError, type CostModelDef } from "./engine.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const modelsDir = join(repoRoot, "models");
const golden = JSON.parse(readFileSync(join(modelsDir, "tests", "golden.json"), "utf8"));

test("expression evaluator matches Python semantics", () => {
  assert.equal(evaluate("2 + 3 * 4", {}), 14);
  assert.equal(evaluate("(2 + 3) * 4", {}), 20);
  assert.equal(evaluate("a / b - c", { a: 10, b: 4, c: 0.5 }), 2.0);
  assert.equal(evaluate("-a + 5", { a: 2 }), 3);
  assert.throws(() => evaluate("a + b", { a: 1 }), FormulaError);
  assert.throws(() => evaluate("1 / z", { z: 0 }), FormulaError);
  assert.throws(() => evaluate("f(1)", { f: 1 }), FormulaError);
});

test("golden fixture covers every model in /models", () => {
  const files = readdirSync(modelsDir).filter((f) => f.endsWith(".yaml"));
  assert.equal(files.length, golden.models.length);
});

for (const entry of golden.models) {
  test(`golden parity: ${entry.id}`, () => {
    const model = parse(
      readFileSync(join(modelsDir, `${entry.id}.yaml`), "utf8"),
    ) as CostModelDef;
    assert.equal(model.version, entry.version, "version drift — regenerate golden");
    const result = evaluateRange(model);
    const close = (a: number, b: number) => assert.ok(Math.abs(a - b) < 1e-6, `${a} != ${b}`);
    close(result.p10, entry.p10);
    close(result.p50, entry.p50);
    close(result.p90, entry.p90);
    assert.deepEqual(result.directions, entry.directions);
    for (const [key, value] of Object.entries(entry.central_components as Record<string, number>)) {
      close(result.centralValues[key], value);
    }
  });
}
