"""Regenerate models/tests/golden.json — the shared fixture that pins the
Python and TypeScript engines to identical output.

    uv run --directory pipelines python scripts/gen_golden.py

Run deliberately when a model or the engine changes, and commit the diff with
the change that caused it.
"""

from __future__ import annotations

import json

from pipelines import MODELS_DIR
from pipelines.costmodel.engine import evaluate_range, load_all_models


def main() -> None:
    entries = []
    for model in load_all_models():
        result = evaluate_range(model)
        entries.append(
            {
                "id": model.id,
                "version": model.version,
                "primary_output": model.primary_output,
                "unit": model.unit,
                "p10": result.p10,
                "p50": result.p50,
                "p90": result.p90,
                "directions": result.directions,
                "central_components": {
                    f.key: result.central_values[f.key] for f in [*model.components, *model.outputs]
                },
            }
        )
    out = MODELS_DIR / "tests" / "golden.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"_comment": "Generated by pipelines/scripts/gen_golden.py — do not edit by hand.", "models": entries}, indent=2) + "\n")
    print(f"wrote {out} ({len(entries)} models)")


if __name__ == "__main__":
    main()
